spring:
   datasource:
      username: little_free_library
      password: little_free_library
      url: jdbc:mysql://localhost:3306/little_free_library
 
   jpa:
      hibernate:
         ddl-auto: none
      show-sql: true
      
   sql:
      init:
         mode: never